# This is a sample build configuration for Java (Maven).
# Check our guides at https://confluence.atlassian.com/x/zd-5Mw for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: maven:3.3.9

pipelines:
  default:
    - step:
        name: Build and Package
        caches:
          - maven
        script: # Modify the commands below to build your repository.
          #- mvn -B verify # -B batch mode makes Maven less verbose
          - ls -la
          - mvn -version
          - chmod +x *.sh
          - ./build-start.sh -f $SERVICES_PACKAGE_NAME -r $BITBUCKET_BUILD_NUMBER
          - curl -X POST --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads" --form files=@"${SERVICES_PACKAGE_NAME}.${BITBUCKET_BUILD_NUMBER}.tar.gz"
    - step:
        name: Stage deployment
        script:
          - curl -s -L --user "${BB_AUTH_STRING}" "https://api.bitbucket.org/2.0/repositories/${BITBUCKET_REPO_OWNER}/${BITBUCKET_REPO_SLUG}/downloads/${SERVICES_PACKAGE_NAME}.${BITBUCKET_BUILD_NUMBER}.tar.gz" -o "${SERVICES_PACKAGE_NAME}.${BITBUCKET_BUILD_NUMBER}.tar.gz"
          #- mkdir -p ~/.ssh
          #- cat my_known_hosts >> ~/.ssh/known_hosts
          #- chmod -R 0700 ~/.ssh
          - chmod 0700 id_rsa.ppk
          - sftp -i id_rsa.ppk bitbucket-pipeline@menageadultclub.com
          #- ll -rt
          #- whoami
          #- ./stage-package.sh -f $SERVICES_PACKAGE_NAME -r $BITBUCKET_BUILD_NUMBER
